version: '3.9'
services:
  api_server:
    container_name: api_server
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true # コンテナの永続化
    env_file:
      - ./app/.go_env
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.28
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_simple_todo
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
